### PR TITLE
Update 1.1.25.sh

### PR DESCRIPTION
**Pull request by yoavrotems**
Update it to limit output

### CODE REVIEW

**Comment by yoavrotems** [comment]
It won't work to move the head before 2>/dev/null because then the substream stderr won't direct to /dev/null but to stdout

**Comment by yoavAqua** [comment]
@yoavrotems I believe that this file (1.1.25.sh) is not necessary, can you move back the content of the file to be the audit command of test 1.1.25 please?

**Comment by lizrice** [comment]
@yoavrotems is this change still needed? Should we be merging it?

**Comment by yoavrotems** [comment]
The limit with head is still needed but It could be returned to be audit command and not bash script.
I would do it

**Pull request merged**
